import { content } from "./content";
import { ContactForm } from "../components/contact-form";
export default function Home() {
return <><a className="skip" href="#main">Skip to content</a>
<header id="home" className="header"><div className="wrap navigation"><a className="brand" href="#home">{content.name}</a><nav aria-label="Main navigation"><a href="#about">Biography</a><a href="#kind-words">Testimonials</a><a href="#contact">Contact</a></nav></div></header>
<main id="main">
<section className="opening" id="about" aria-labelledby="name"><div className="wrap"><div className="opening-rule"><span>01 / Biography</span><span>{content.descriptor}</span></div><div className="bio-grid"><div className="bio"><h1 id="name">{content.name}<span aria-hidden="true">.</span></h1><div className="bio-copy">{content.bio.map(p => <p key={p}>{p}</p>)}</div><p className="placeholder">Biography placeholder</p><a className="button" href="#contact">Contact</a></div><figure><div className="portrait-frame">{content.headshot ? <img src={content.headshot} alt={content.headshotAlt} width="720" height="900"/> : <div className="portrait-slot"><span>insert headshot here</span></div>}</div></figure></div></div></section>
<section id="testimonials" className="testimonials" aria-labelledby="words"><div className="wrap"><div className="section-heading"><span className="eyebrow">02 / Testimonials</span><h2 id="words">Testimonials</h2></div><p className="placeholder">Placeholder text · Replace with approved testimonials.</p><div className="quotes">{content.testimonials.map((t) => <article key={t.name}><div className="quote-heading"><h3>{t.name}</h3></div><p>{t.text}</p></article>)}</div></div></section>
<section className="contact" id="contact" aria-labelledby="contact-heading"><div className="wrap contact-grid"><div><span className="eyebrow">03 / Contact</span><h2 id="contact-heading">Contact</h2><div className="contact-links">{content.email ? <a href={`mailto:${content.email}`}>{content.email}</a> : <span>Email address coming soon</span>}{content.instagramUrl ? <a href={content.instagramUrl} target="_blank" rel="noopener noreferrer">Instagram ↗</a> : <span>Instagram · coming soon</span>}</div></div><ContactForm email={content.email}/></div></section>
</main><footer className="wrap footer"><span>© {new Date().getFullYear()} {content.name}</span><a href="#home">Back to top ↑</a></footer></>;
}
