import { content } from "./content";
import { ContactForm } from "../components/contact-form";

export default function Home() {
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <header className="header wrap"><a className="wordmark" href="#home">{content.name}<span className="wordmark-dot">.</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#kind-words">Kind words</a><a className="nav-contact" href="#contact">Get in touch <span aria-hidden="true">↗</span></a></nav></header>
    <main id="main">
      <section className="hero wrap" id="home" aria-labelledby="hero-title"><div className="eyebrow"><span/> {content.descriptor} <span/></div><h1 id="hero-title">{content.title}<br/><em>{content.titleAccent}</em></h1><p className="hero-copy">{content.introduction}</p><a className="button" href="#contact">Let’s begin a conversation <span aria-hidden="true">↗</span></a><div className="hero-foot"><span>Care in the details. Connection at the heart.</span><a href="#about">A little more about me <span aria-hidden="true">↓</span></a></div></section>
      <section className="about wrap section" id="about" aria-labelledby="about-title"><div className="portrait-block"><div className="portrait-frame">{content.headshot ? <img src={content.headshot} alt={content.headshotAlt} width="680" height="850"/> : <div className="portrait-slot"><span className="portrait-initials" aria-hidden="true">YN</span><span className="portrait-caption">Your portrait here</span></div>}</div><div className="portrait-note"><span>A face behind the work</span><span aria-hidden="true">01 /</span></div></div><div className="bio"><p className="eyebrow">01 — Introduction</p><h2 id="about-title">{content.bioTitle}</h2><p className="bio-lead">An individual approach.<br/><em>A human connection.</em></p>{content.bio.map(p => <p key={p}>{p}</p>)}<p className="draft-label">Biography placeholder</p><a className="text-link" href="#contact">I’d love to hear from you <span aria-hidden="true">↗</span></a></div></section>
      <section className="testimonials" id="kind-words" aria-labelledby="words-title"><div className="wrap section"><div className="section-heading"><div><p className="eyebrow">02 — Kind words</p><h2 id="words-title">In good company.</h2></div><p>A few reflections from the people<br/>who make the work meaningful.</p></div><p className="draft-label testimonial-note">Content slots — replace with approved testimonials before publishing.</p><div className="quotes">{content.testimonials.map((item, i) => <article className="quote" key={item.name}><div className="quote-top"><span aria-hidden="true">“</span><span className="eyebrow">0{i+1}</span></div><h3>{item.title}</h3><p>{item.text}</p><footer><span className="quote-name">{item.name}</span><span className="draft-label">Testimonial placeholder</span></footer></article>)}</div></div></section>
      <section className="contact" id="contact" aria-labelledby="contact-title"><div className="wrap section contact-grid"><div><p className="eyebrow">03 — A note to say hello</p><h2 id="contact-title">Every connection<br/>starts with <em>hello.</em></h2><p>Have a question or something in mind?<br/>I’d love to hear from you.</p><div className="contact-links">{content.email ? <a href={`mailto:${content.email}`}>{content.email}</a> : <span>Email address coming soon</span>}{content.instagramUrl ? <a href={content.instagramUrl} target="_blank" rel="noopener noreferrer">{content.instagramLabel} ↗</a> : <span>Instagram · coming soon</span>}</div></div><ContactForm email={content.email}/></div></section>
    </main><footer className="footer wrap"><a className="wordmark" href="#home">{content.name}.</a><p>© {new Date().getFullYear()} {content.name}</p><a href="#home">Back to top ↑</a></footer>
  </>;
}
